from .logic_value import LogicValue as LogicValue
from .node import Node as Node
from abc import ABC
from enum import IntEnum

class LogicDeviceKind(IntEnum):
    GND = 0
    VDD = 1
    INPUT = 2
    PROBE = 3
    PORT = 4

class LogicDevice(ABC):
    def __init__(self, device_id: int, kind: LogicDeviceKind, node: Node) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def kind(self) -> LogicDeviceKind: ...
    @property
    def terminal(self) -> Node: ...
    @property
    def terminal_default_value(self) -> LogicValue: ...
    @property
    def terminal_resolved_value(self) -> LogicValue: ...

class VDD(LogicDevice):
    def __init__(self, device_id: int, node: Node) -> None: ...

class GND(LogicDevice):
    def __init__(self, device_id: int, node: Node) -> None: ...

class Input(LogicDevice):
    def __init__(self, device_id: int, node: Node) -> None: ...
    def set_value(self, value: LogicValue) -> None: ...

class Probe(LogicDevice):
    def __init__(self, device_id: int, node: Node) -> None: ...
    def sample(self) -> LogicValue: ...

class Port(LogicDevice):
    def __init__(self, device_id: int, node: Node) -> None: ...
