from enum import IntEnum
from sirc.core import LogicValue as LogicValue

class NodeKind(IntEnum):
    BASE = 0
    GATE = 1

class Node:
    def __init__(self, node_id: int, kind: NodeKind = ...) -> None: ...
    def set_default_value(self, value: LogicValue) -> None: ...
    @property
    def default_value(self) -> LogicValue: ...
    def set_resolved_value(self, value: LogicValue) -> None: ...
    @property
    def resolved_value(self) -> LogicValue: ...
    @property
    def id(self) -> int: ...
    @property
    def kind(self) -> NodeKind: ...
