from sirc.core.logic import LogicValue as LogicValue

class Node:
    def __init__(self) -> None: ...
    def set_default_value(self, value: LogicValue) -> None: ...
    @property
    def default_value(self) -> LogicValue: ...
    def set_resolved_value(self, value: LogicValue) -> None: ...
    @property
    def resolved_value(self) -> LogicValue: ...
    def add_connection(self, other: Node) -> None: ...
    def remove_connection(self, other: Node) -> None: ...
    def connect(self, other: Node) -> None: ...
    def disconnect(self, other: Node) -> None: ...
    def get_connections(self) -> set[Node]: ...
