import abc
from abc import ABC, abstractmethod
from sirc.core.logic import LogicValue as LogicValue
from sirc.core.node import Node as Node

class Transistor(ABC, metaclass=abc.ABCMeta):
    def __init__(self) -> None: ...
    @property
    def gate(self) -> Node: ...
    @property
    def source(self) -> Node: ...
    @property
    def drain(self) -> Node: ...
    @abstractmethod
    def is_conducting(self) -> bool: ...
    def terminals(self) -> tuple[Node, Node, Node]: ...
    def conduction_nodes(self) -> tuple[Node, Node]: ...

class NMOS(Transistor):
    def is_conducting(self) -> bool: ...

class PMOS(Transistor):
    def is_conducting(self) -> bool: ...
