import abc
from .logic_value import LogicValue as LogicValue
from .node import Node as Node, NodeKind as NodeKind
from abc import ABC, abstractmethod
from enum import IntEnum

class TransistorKind(IntEnum):
    NMOS = 0
    PMOS = 1

class Transistor(ABC, metaclass=abc.ABCMeta):
    def __init__(self, transistor_id: int, kind: TransistorKind, gate: Node, source: Node, drain: Node) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def kind(self) -> TransistorKind: ...
    @property
    def gate(self) -> Node: ...
    @property
    def source(self) -> Node: ...
    @property
    def drain(self) -> Node: ...
    @abstractmethod
    def is_conducting(self) -> bool: ...
    def terminals(self) -> tuple[Node, Node, Node]: ...
    def conduction_nodes(self) -> tuple[Node, Node]: ...

class NMOS(Transistor):
    def __init__(self, transistor_id: int, gate: Node, source: Node, drain: Node) -> None: ...
    def is_conducting(self) -> bool: ...

class PMOS(Transistor):
    def __init__(self, transistor_id: int, gate: Node, source: Node, drain: Node) -> None: ...
    def is_conducting(self) -> bool: ...
