class IdentificationFactory:
    def __init__(self) -> None: ...
    def allocate_node_id(self) -> int: ...
    def allocate_device_id(self) -> int: ...
    def allocate_transistor_id(self) -> int: ...
