from dataclasses import dataclass, field
from sirc.core.device import LogicDevice as LogicDevice
from sirc.core.logic import LogicValue as LogicValue
from sirc.core.node import Node as Node
from sirc.core.transistor import Transistor as Transistor
from typing import Iterable

@dataclass(eq=False)
class NodeComponent:
    nodes: set[Node] = field(default_factory=set[Node])

class DeviceSimulator:
    def __init__(self) -> None: ...
    def register_device(self, device: LogicDevice) -> None: ...
    def register_devices(self, devices: Iterable[LogicDevice]) -> None: ...
    def register_transistor(self, transistor: Transistor) -> None: ...
    def register_transistors(self, transistors: Iterable[Transistor]) -> None: ...
    def unregister_device(self, device: LogicDevice) -> None: ...
    def unregister_devices(self, devices: Iterable[LogicDevice]) -> None: ...
    def unregister_transistor(self, transistor: Transistor) -> None: ...
    def unregister_transistors(self, transistors: Iterable[Transistor]) -> None: ...
    def build_topology(self) -> None: ...
    def connect(self, a: Node, b: Node) -> None: ...
    def disconnect(self, a: Node, b: Node) -> None: ...
    def tick(self) -> None: ...
