from ..core.logic_device import GND as GND, Input as Input, LogicDevice as LogicDevice, Port as Port, Probe as Probe, VDD as VDD
from ..core.node import Node as Node, NodeKind as NodeKind
from ..core.transistor import NMOS as NMOS, PMOS as PMOS, Transistor as Transistor

class IdentificationFactory:
    def __init__(self) -> None: ...
    def allocate_node_id(self) -> int: ...
    def allocate_device_id(self) -> int: ...
    def allocate_transistor_id(self) -> int: ...

class NodeFactory:
    def __init__(self, id_factory: IdentificationFactory) -> None: ...
    def create_base_node(self) -> Node: ...
    def create_gate_node(self) -> Node: ...

class LogicDeviceFactory:
    def __init__(self, id_factory: IdentificationFactory, node_factory: NodeFactory) -> None: ...
    def create_vdd(self) -> VDD: ...
    def create_gnd(self) -> GND: ...
    def create_input(self) -> Input: ...
    def create_probe(self) -> Probe: ...
    def create_port(self) -> Port: ...

class TransistorFactory:
    def __init__(self, id_factory: IdentificationFactory, node_factory: NodeFactory) -> None: ...
    def create_nmos(self) -> NMOS: ...
    def create_pmos(self) -> PMOS: ...

class DeviceSimulatorState:
    nodes: list[Node]
    devices: list[LogicDevice]
    transistors: list[Transistor]
    wires: list[tuple[int, int]]
    wires_cache: dict[tuple[int, int], int]
    reference_static_neighbors: list[list[int]]
    reference_components: list[list[int]]
    reference_component_id: list[int]
    def __init__(self) -> None: ...
