from ..core.node import Node as Node, NodeKind as NodeKind

class IdentificationFactory:
    def __init__(self) -> None: ...
    def allocate_node_id(self) -> int: ...
    def allocate_device_id(self) -> int: ...
    def allocate_transistor_id(self) -> int: ...

class NodeFactory:
    def __init__(self, id_factory: IdentificationFactory) -> None: ...
    def create_base_node(self) -> Node: ...
    def create_gate_node(self) -> Node: ...
