from ..core.logic_device import GND as GND, Input as Input, LogicDevice as LogicDevice, Port as Port, Probe as Probe, VDD as VDD
from ..core.node import Node as Node
from ..core.transistor import NMOS as NMOS, PMOS as PMOS, Transistor as Transistor
from .device_dep import DeviceSimulatorState as DeviceSimulatorState, IdentificationFactory as IdentificationFactory, LogicDeviceFactory as LogicDeviceFactory, NodeFactory as NodeFactory, TransistorFactory as TransistorFactory

class DeviceSimulator:
    def __init__(self) -> None: ...
    def create_vdd(self) -> VDD: ...
    def create_gnd(self) -> GND: ...
    def create_input(self) -> Input: ...
    def create_probe(self) -> Probe: ...
    def create_port(self) -> Port: ...
    def create_nmos(self) -> NMOS: ...
    def create_pmos(self) -> PMOS: ...
    def connect(self, node_a: Node, node_b: Node) -> None: ...
    def disconnect(self, node_a: Node, node_b: Node) -> None: ...
    def build_topology(self) -> None: ...
    def tick(self) -> None: ...
